# Default values for aikininnovations.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: josmo/aikininnovations
  tag: latest
  pullPolicy: Always

service:
  enabled: true
  type: ClusterIP
  port: 80

annotations:
  buildNumber: 0
  deployedDate: 0000-00-00

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - www.aikininnovations.com
  tls:
    - secretName: www-aikininnovations-com-tls
      hosts:
        - www.aikininnovations.com

resources:
  limits:
    cpu: 10m
    memory: 5Mi
  requests:
    cpu: 2m
    memory: 2Mi

nodeSelector: {}

tolerations: []

affinity: {}
